### ISSUE TITLE
Используем docker для веб-разработки на php

### ISSUE THREAD

**Issue by d-nikolaev** [EgorBanin/EgorBanin.github.io#1]
у вас: docker compose up -d
а работает так : docker-compose up -d

**Comment by EgorBanin** [comment]
compose теперь часть docker https://docs.docker.com/compose/migrate/. Тут нет ошибки.

**Comment by d-nikolaev** [comment]
понял, не знал.
но в моём случае сработал этот вариант docker-compose up -d
скорее всего из-за версии docker в системе.
